musicProject/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('songApp.urls')),
] + static(settings.MEDIA_URL,
           document_root=settings.MEDIA_ROOT)

songApp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('signin', views.signin, name='signin'),
    path('signup', views.signup, name='signup'),
    path('signout/', views.signout, name='signout'),
    path('index', views.index, name='index'),
    path('add_song', views.add_song, name='add_song'),
    path('my_song', views.my_song, name='my_song'),
    path('blog', views.blog, name='blog'),
    path('contact', views.contact, name='contact'),
    path('elements', views.elements, name='elements'),
    path('track', views.track, name='track'),
    path('about', views.about, name='about'),
    path('blog', views.blog, name='blog'),    
    # path('indexout', views.indexout, name='indexout'),
    path('loginnew', views.loginnew, name='loginnew'),
    path('public_song', views.public_song, name='public_song'),
    path('verify', views.verify, name='verify'),
    path('check_otp', views.check_otp, name='check_otp'),
    path('error', views.error, name='error'),
]

songApp/models.py
from django.db import models
from django.contrib.auth.models import User


class userInfo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    mobile_number = models.CharField(max_length=10)
    verified = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


class Song(models.Model):
    SONG_CHOICES = [
        ("Public", "Public"),
        ("Private", "Private"),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    # user = models.CharField(max_length=100,id='noom', null=True)
    audio_name = models.CharField(max_length=100)
    audio_file = models.FileField(upload_to='music/', blank=True, null=True)
    audio_type = models.CharField(max_length=20, choices=SONG_CHOICES)
    thumbnail = models.ImageField(upload_to='thumbnail/', default='thumbnail/default.jpg', null=True, blank=True)

    def __str__(self):
        return self.user.username + "  " + self.audio_name

templates/add_song_recover.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Add Song</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <link rel='stylesheet' href='static/addsong.css'>

    <style>
        #id_user {
            display: none;
        }
    </style>

</head>

<body>
    {% if request.user.is_authenticated %} {% if chk %}
    <div class="login-form">
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <h1>Add Song</h1>
            {{song_form.errors}} {{song_form.as_p}}
            <div class="content">

                <input type="hidden" name="user" class="form-control" value="" id="elder" />
                <!-- <p> <select name="user" required id="id_user elder">
  <option value="" selected>---------</option>

  <option value="716125790292148225">q</option>

  <option value="716140495304720385">user</option>

  <option value="716202724541431809">tapan</option>

  <option value="716205605339267073">dev</option>

  <option value="716218622960631809">w</option>

</select></p> -->

                <div class="input-field">
                    <label for="id_audio_name">Audio name:</label> <input type="text" name="audio_name" maxlength="100" required="" id="id_audio_name">
                </div>

                <div class="input-field">
                    <p><label for="id_audio_file">Audio file:</label> <input type="file" name="audio_file" id="id_audio_file"></p>
                </div>

                <div class="input-field">
                    <p><label for="id_audio_type">Audio type:</label> <select name="audio_type" required="" id="id_audio_type">
                     <option value="" selected="">---------</option>
      
                      <option value="Public">Public</option>
      
                         <option value="Private">Private</option>
      
                         </select></p>
                </div>

                <div class="input-field">
                    <p><label for="id_thumbnail">Thumbnail:</label> <input type="file" name="thumbnail" accept="image/*" id="id_thumbnail"></p>
                </div>


            </div>

            <button type="submit">Add Song</button>


        </form>
    </div>
    {% else %}


    <div style="color: red;">
        Your mobile number is not verified, to add song <a href="{% url 'verify' %}">Verify</a> it.
    </div>

    {% endif %} {% else %}
    <h3>
        <a href="{% url 'signin' %}"> Please login first!</a>
    </h3>
    {% endif %}

    <!-- footer start -->
    <footer class="footer">
        <!-- <div class="footer_top">
        <div class="container">
            <div class="row">
                <div class="col-xl-6 col-md-6">
                    <div class="footer_widget">
                        <h3 class="footer_title">
                            Services
                        </h3>
                        <div class="subscribe-from">
                            <form action="#">
                                <input type="text" placeholder="Enter your mail">
                                <button type="submit">Subscribe</button>
                            </form>
                        </div>
                        <p class="sub_text">Esteem spirit temper too say adieus who direct esteem esteems luckily.</p>
                    </div>
                </div>
                <div class="col-xl-5 col-md-5 offset-xl-1">
                    <div class="footer_widget">
                        <h3 class="footer_title">
                            Contact Me
                        </h3>
                        <ul>
                            <li><a href="#">conbusi@support.com
                                </a></li>
                            <li><a href="#">+10 873 672 6782
                                </a></li>
                            <li><a href="#">600/D, Green road, Kings Garden NewYork-6732</a></li>
                        </ul>
                        <div class="socail_links">
                            <ul>
                                <li>
                                    <a href="#">
                                        <i class=" fa fa-facebook "></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="fa fa-google-plus"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="fa fa-twitter"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="fa fa-youtube-play"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="fa fa-instagram"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div> -->
        <div class="copy-right_text">
            <div class="container">
                <div class="footer_border"></div>
                <div class="row">
                    <div class="col-xl-7 col-md-6">
                        <p class="copy_right">
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            Copyright &copy;
                            <script>
                                document.write(new Date().getFullYear());
                            </script> All rights reserved | This Website is made with<i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="" target="_blank">Debug Thugs</a>
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        </p>
                    </div>
                    <div class="col-xl-5 col-md-6">
                        <div class="footer_links">
                            <ul>
                                <li><a href="{% url 'home' %}">home</a></li>
                                <li><a href="{% url 'about' %}">about</a></li>
                                <li><a href="{% url 'track' %}">tracks</a></li>
                                <li><a href="{% url 'contact' %}">contact</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!--/ footer end  -->


    <!-- {% if request.user.is_authenticated %}

    <form action="" method="post" enctype="multipart/form-data">

        {% csrf_token %} {{song_form.as_p}} {{song_form.errors}}

        <button type="submit">Submit</button>

    </form>
    {% else %}
    <h3>
        <a href="{% url 'signin' %}"> Please login first!</a>
    </h3>
    {% endif %} -->

    <!-- <script>
        var name1 = {{user.id}};

        document.getElementById("elder").value = name1;
    </script> -->



</body>

</html>

templates/check_otp.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>OTP Verification HTML Template</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css">
    <link rel="stylesheet" href="../static/verify.css">

</head>

<body>
    <div class="bgImage"></div>
    <svg class="blobCont">
    <image xlink:href="https://images.unsplash.com/photo-1500462918059-b1a0cb512f1d?ixlib=rb-0.3.5&s=e20bc3d490c974d9ea190e05c47962f5&auto=format&fit=crop&w=634&q=80" mask="url(#mask)" width="100%" height="100%" preserveAspectRatio="xMidYMid slice" />
    <defs>
        <filter id="gooey" height="130%">
            <feGaussianBlur in="SourceGraphic" stdDeviation="15" result="blur" />
            <feColorMatrix in="blur" mode="matrix" values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 18 -7" result="goo" />
        </filter>
    </defs>
    <mask id="mask" x="0" y="0">
        <g style="filter: url(#gooey)">
            <circle class="blob" cx="10%" cy="10%" r="80" fill="white" stroke="white"/>
            <circle class="blob" cx="50%" cy="10%" r="40" fill="white" stroke="white"/>
            <circle class="blob" cx="17%" cy="15%" r="70" fill="white" stroke="white"/>
            <circle class="blob" cx="90%" cy="20%" r="120" fill="white" stroke="white"/>
            <circle class="blob" cx="30%" cy="25%" r="30" fill="white" stroke="white"/>
            <circle class="blob" cx="50%" cy="60%" r="80" fill="white" stroke="white"/>
            <circle class="blob" cx="70%" cy="90%" r="10" fill="white" stroke="white"/>
            <circle class="blob" cx="90%" cy="60%" r="90" fill="white" stroke="white"/>
            <circle class="blob" cx="30%" cy="90%" r="80" fill="white" stroke="white"/>
            <circle class="blob" cx="10%" cy="10%" r="80" fill="white" stroke="white"/>
            <circle class="blob" cx="50%" cy="10%" r="20" fill="white" stroke="white"/>
            <circle class="blob" cx="17%" cy="15%" r="70" fill="white" stroke="white"/>
            <circle class="blob" cx="40%" cy="20%" r="120" fill="white" stroke="white"/>
            <circle class="blob" cx="30%" cy="25%" r="30" fill="white" stroke="white"/>
            <circle class="blob" cx="80%" cy="60%" r="80" fill="white" stroke="white"/>
            <circle class="blob" cx="17%" cy="10%" r="100" fill="white" stroke="white"/>
            <circle class="blob" cx="40%" cy="60%" r="90" fill="white" stroke="white"/>
            <circle class="blob" cx="10%" cy="50%" r="80" fill="white" stroke="white"/>
        </g>
    </mask>
</svg>

    <!-- partial:index.partial.html -->
    <!-- multistep form -->
    <form id="msform" method="post">


        <!-- step 1 -->
        <fieldset>
            <h2 class="h2">SMS Validation</h2>
            <h3 class="h3">{% csrf_token %} Enter your OTP below</h3>
            <!--<label>Name</label>-->

            <input type="text" name="otp" placeholder="Enter OTP Here" />

            <input type="submit" name="next" class="next action-button" value="Submit" />

        </fieldset>
    </form>






    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha256-4+XzXVhsDmqanXGHaHvgh1gMQKX40OUvDEBTu8JcmNs=" crossorigin="anonymous"></script>
    <!-- jQuery easing plugin -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js" type="text/javascript"></script>
    <!-- partial -->
    <script src="../static/script.js"></script>
    <script type="257be86a981729866f2fa61c-text/javascript">
        (function(i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r;
            i[r] = i[r] || function() {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date();
            a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)
        })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-83834093-1', 'auto');
        ga('send', 'pageview');
    </script>
</body>

</html>

templates/error.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>Error</h1>

    <h1>To view this page <a href="{% url 'loginnew' %}"> login</a> or <a href="{% url 'loginnew' %}"> register</a> yourself!</h1>

</body>

</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>Welcome to beautyful world of god!</h1>

    {% if request.user.is_authenticated %}

    <a href="{% url 'signout' %}">Signout</a> <br> {% else %}

    <a href="{% url 'loginnew' %}">Login / Sign Up</a> <br> {% endif %}

</body>

</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Login/Sign Up</title>
    <link rel="shortcut icon" type="image/x-icon" href="../static/assets1/img/favicon.png">
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Open+Sans:600'>
    <link rel="stylesheet" href="static/login.css">


</head>

<body>

    <!-- partial:index.partial.html -->
    <div style="padding-top: 4em; padding-bottom: 4em;">
        <div class="login-wrap">
            <div class="login-html">
                <input id="tab-1" type="radio" name="tab" class="sign-in" checked><label for="tab-1" class="tab">Sign In</label>
                <input id="tab-2" type="radio" name="tab" class="sign-up"><label for="tab-2" class="tab">Sign Up</label>
                <div class="login-form">
                    <form action="{% url 'signin' %}" method="POST">
                        {% csrf_token %}
                        <div class="sign-in-htm">
                            <div class="group">
                                <label for="user" class="label">Username</label>
                                <input name="username" id="floatingInput" type="text" class="input">
                            </div>
                            <div class="group">
                                <label for="pass" class="label">Password</label>
                                <input name="password" id="floatingPassword" type="password" class="input" data-type="password">
                            </div>
                            <!-- <div class="group">
                            <input id="check" type="checkbox" class="check" checked>
                            <label for="check"><span class="icon"></span> Keep me Signed in</label>
                        </div> -->
                            <div class="group">
                                <input type="submit" class="button" value="Sign In">
                            </div>
                    </form>
                    <div class="hr"></div>
                    <!-- <div class="foot-lnk">
                    <a href="#forgot">Forgot Password?</a>
                </div> -->
                    <div class="foot-lnk">
                        <label for="tab-2">Not a Member yet?</a>
            </div>
                </div>
                <div class="sign-up-htm">
                    <form action="{% url 'signup' %}" method="POST">
                        {% csrf_token %}
                        <div class="group">
                            <label for="user" class="label">Username</label>
                        <input type="text" class="input" name="username" maxlength="150" required="" id="id_username">

                    </div>
                    <div class="group">
                        <label for="pass" class="label">Email Id</label>
                        <input type="email" class="input" name="email" maxlength="254" id="id_email">
                    </div>
                    <div class="group">
                        <label for="pass" class="label">Mobile Number</label>
                        <input type="text" class="input" name="mobile_number" maxlength="10" required="" id="id_mobile_number">
                    </div>
                    <div class="group">
                        <label for="pass" class="label">Password</label>
                        <input type="password" class="input" name="password" required="" id="id_password">
                    </div>

                    <div class="group">
                        <input type="submit" class="button" value="Sign Up">
                    </div>
                    </form>
                    <div class="hr"></div>
                    <div class="foot-lnk">
                        <label for="tab-1">Already Member?</a>
				</div>
			</div>
		</div>
	</div>
<!-- partial -->
    
</body>
</html>

templates/main.html
<a href="https://colorlib.com/wp/templates/"><img src="https://colorlib.com/wp/wp-content/uploads/sites/2/colorlib-push-logo.png" alt="Colorlib logo"></a>
<h1 style="text-align:center;">Thank you for using our template!</h1>
<p style="text-align:center;">For more awesome templates please visit <strong><a href="https://colorlib.com/wp/templates/">Colorlib</a></strong>.</p>
<br>
<p style="text-align:center; color:red;"><strong>Copyright information for the template can't be altered/removed unless you purchase a license.</strong>

<p style="text-align:center;"><strong>Removing copyright information without the license will result in suspension of your hosting and/or domain name(s).</strong>

<p style="text-align:center;"><strong>More information about the license is available <a href="https://colorlib.com/wp/licence/">here</a></strong>.</p>

<style>
img {
  margin: 0 auto;
  display: block;
  margin-top: 20%;
}
</style>

templates/verify.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>OTP Verification HTML Template</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css">
    <link rel="stylesheet" href="../static/verify.css">

</head>

<body>
    <div class="bgImage"></div>
    <svg class="blobCont">
    <image xlink:href="https://images.unsplash.com/photo-1500462918059-b1a0cb512f1d?ixlib=rb-0.3.5&s=e20bc3d490c974d9ea190e05c47962f5&auto=format&fit=crop&w=634&q=80" mask="url(#mask)" width="100%" height="100%" preserveAspectRatio="xMidYMid slice" />
    <defs>
        <filter id="gooey" height="130%">
            <feGaussianBlur in="SourceGraphic" stdDeviation="15" result="blur" />
            <feColorMatrix in="blur" mode="matrix" values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 18 -7" result="goo" />
        </filter>
    </defs>
    <mask id="mask" x="0" y="0">
        <g style="filter: url(#gooey)">
            <circle class="blob" cx="10%" cy="10%" r="80" fill="white" stroke="white"/>
            <circle class="blob" cx="50%" cy="10%" r="40" fill="white" stroke="white"/>
            <circle class="blob" cx="17%" cy="15%" r="70" fill="white" stroke="white"/>
            <circle class="blob" cx="90%" cy="20%" r="120" fill="white" stroke="white"/>
            <circle class="blob" cx="30%" cy="25%" r="30" fill="white" stroke="white"/>
            <circle class="blob" cx="50%" cy="60%" r="80" fill="white" stroke="white"/>
            <circle class="blob" cx="70%" cy="90%" r="10" fill="white" stroke="white"/>
            <circle class="blob" cx="90%" cy="60%" r="90" fill="white" stroke="white"/>
            <circle class="blob" cx="30%" cy="90%" r="80" fill="white" stroke="white"/>
            <circle class="blob" cx="10%" cy="10%" r="80" fill="white" stroke="white"/>
            <circle class="blob" cx="50%" cy="10%" r="20" fill="white" stroke="white"/>
            <circle class="blob" cx="17%" cy="15%" r="70" fill="white" stroke="white"/>
            <circle class="blob" cx="40%" cy="20%" r="120" fill="white" stroke="white"/>
            <circle class="blob" cx="30%" cy="25%" r="30" fill="white" stroke="white"/>
            <circle class="blob" cx="80%" cy="60%" r="80" fill="white" stroke="white"/>
            <circle class="blob" cx="17%" cy="10%" r="100" fill="white" stroke="white"/>
            <circle class="blob" cx="40%" cy="60%" r="90" fill="white" stroke="white"/>
            <circle class="blob" cx="10%" cy="50%" r="80" fill="white" stroke="white"/>
        </g>
    </mask>
</svg>

    <!-- partial:index.partial.html -->
    <!-- multistep form -->
    <form id="msform" method="post">


        <!-- step 1 -->
        <fieldset>
            <h2 class="h2">{% csrf_token %} Are you sure want to verify number XXXXXXXX{{mobile_number}} ? <br></h2>
            <h3 class="h3">Choose a way to verify</h3>
            <input type="submit" name="call" class="next action-button" value="call" />
            <input type="submit" name="sms" class="next action-button" value="sms" />

        </fieldset>
    </form>






    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha256-4+XzXVhsDmqanXGHaHvgh1gMQKX40OUvDEBTu8JcmNs=" crossorigin="anonymous"></script>
    <!-- jQuery easing plugin -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js" type="text/javascript"></script>
    <!-- partial -->
    <script src="../static/script.js"></script>
    <script type="257be86a981729866f2fa61c-text/javascript">
        (function(i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r;
            i[r] = i[r] || function() {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date();
            a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)
        })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-83834093-1', 'auto');
        ga('send', 'pageview');
    </script>
</body>

</html>